### ISSUE TITLE
Add config file to adjust the dump output format

### ISSUE THREAD

**Issue by Jawkx** [Jawkx/dump#1]
Adding a config file to adjust the output format

Initial draft:

smthing like this 

``` toml
# ~/.config/dump/config.toml || ~/.dump.toml

file_start = "==== FILE: {{.Filename}} ===="
file_end = "==== END FILE: {{.Filename}} ===="
code_start = "<<<\n{{.Filename}}"
code_end = ">>>"
```
